[[main]]
#name = "Etusivu"
name = "Yhteystiedot"
identifier = "home"
weight = 100
pageRef = "/"

# [[main]]
# name = "Yhteystiedot"
# identifier = "contact"
# weight = 200
# pageRef = "/yhteystiedot/"
