[[main]]
# name = "Framsidan"
name = "Kontaktuppgifter"
identifier = "home"
weight = 100
pageRef = "/"

# [[main]]
# name = "Kontaktuppgifter"
# identifier = "contact"
# weight = 200
# pageRef = "/kontaktuppgifter/"
